# Generated by Django 5.0.2 on 2024-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_source_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='choise',
        ),
    ]
