# Generated by Django 5.0.2 on 2024-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_user_choise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choise',
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(blank=True, choices=[('politics', 'Politics'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('weather', 'Weather'), ('business', 'Business')], max_length=100, null=True),
        ),
    ]
