# Generated by Django 5.0.2 on 2024-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_user_choise_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choice',
            field=models.CharField(blank=True, choices=[('politics', 'Politics'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('weather', 'Weather'), ('business', 'Business')], default=None, max_length=100, null=True),
        ),
    ]
